### ISSUE TITLE
Windows Compilation HowTo Information

### ISSUE THREAD

**Issue by essial** [essial/harvest-rogue#2]
We need howto steps for building on a windows environment. Preferably with both Visual Studio, as well as any other common environments.

**Comment by cwc** [comment]
How do you feel about bundling the PDCurses DLL and include files in a `lib` directory, along with Visual Studio solution and project files? Probably the easiest way for a Windows dev to get rolling.

**Comment by essial** [comment]
Aye, for non linux environments, I'd like to bundle any extra build dependencies as long as it doesn't massively bloat the codebase. .lib/.dll/.h stuff is fine.

I'm a bit iffy on auto-generating the visual studio project as I'd like to let CMake generate it (as they have a gui for that) so that the project's CMake can stay consistent.

If you want to discuss anything, jump on gitter (badge is on the main page); I'll be there.

Thanks again for your help, it's greatly appreciated!
